; PeepoDrumKit 2026/03/15
file_version = 1.0.0

[last_session]
gui_scale = 100
gui_language = 
os_window_swap_interval = 1
os_window_region = 34, 57, 1424, 750
os_window_region_restore = 0, 0, 0, 0
os_window_is_fullscreen = false
os_window_is_maximized = false
show_window_test_menu = false
show_window_help = true
show_window_update_notes = true
show_window_chart_stats = true
show_window_settings = true
show_window_audio_test = false
show_window_tja_import_test = false
show_window_tja_export_test = false
show_window_imgui_demo = false
show_window_imgui_style_editor = false

[recent_files]
; ...
